db.sport.drop();
db.createCollection("sport"});
db.sport.insert({sportId: "1", code: "cricket", displayText: "Cricket"});
db.sport.insert({sportId: "2", code: "football", displayText: "Football"});
db.sport.insert({sportId: "3", code: "lawntennis", displayText: "Lawn Tennis"});
db.sport.insert({sportId: "4", code: "tt", displayText: "Table Tennis"});
db.sport.insert({sportId: "5", code: "squash", displayText: "Squash"});
db.sport.insert({sportId: "6", code: "volleyball", displayText: "Volleyball"});
db.sport.insert({sportId: "7", code: "hockey", displayText: "Hockey"});
db.sport.insert({sportId: "8", code: "cycling", displayText: "Cycling"});
db.sport.insert({sportId: "9", code: "trekking", displayText: "Trekking"});
db.sport.insert({sportId: "10", code: "swimming", displayText: "Swimming"});
db.sport.insert({sportId: "11", code: "running", displayText: "Running"});
db.sport.insert({sportId: "12", code: "basketball", displayText: "Basketball"});
db.sport.insert({sportId: "13", code: "surfing", displayText: "Surfing"});
db.sport.insert({sportId: "14", code: "racing", displayText: "Racing"});
db.sport.insert({sportId: "15", code: "boxing", displayText: "Boxing"});
db.sport.insert({sportId: "16", code: "freesbie", displayText: "Freesbie"});
db.sport.insert({sportId: "17", code: "archery", displayText: "Archery"});
db.sport.insert({sportId: "18", code: "chess", displayText: "Chess"});
db.sport.insert({sportId: "19", code: "carrom", displayText: "Carrom"});
db.sport.insert({sportId: "20", code: "cube", displayText: "Cube"});
db.sport.insert({sportId: "21", code: "snooker", displayText: "Snooker"});
db.sport.insert({sportId: "22", code: "baseball", displayText: "Baseball"});
db.sport.insert({sportId: "23", code: "dodgeball", displayText: "Dodgeball"});
db.sport.insert({sportId: "24", code: "wresting", displayText: "Wrestling"});
db.sport.insert({sportId: "25", code: "golf", displayText: "Golf"});
db.sport.insert({sportId: "26", code: "weightlifting", displayText: "Weight Lifting"});
